# name: create-artifacts

# on:
#   workflow_run:
#     workflows:
#       - verify
#     types:
#       - completed

# jobs:
#   build_n_push_docker_image:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Dump GitHub context
#       env:
#         GITHUB_CONTEXT: ${{ toJson(github) }}
#       run: |
#         echo "$GITHUB_CONTEXT"

#     - name: "Get branch name and save to env"
#       env:
#         IS_PR: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.event == 'pull_request' }}
#       run: |
        
#         if ${IS_PR}; then
#           BRANCH="${{github.event.workflow_run.head_branch}}"
#           BASE_TAG="${BRANCH##*/}"
#         else
#           BRANCH="${{github.event.workflow_run.head_branch}}"
#           BASE_TAG="${BRANCH##*/}"
#         fi

#         echo "BRANCH=${BRANCH}" >> $GITHUB_ENV 
#         echo "BASE_TAG=${BASE_TAG}" >> $GITHUB_ENV 
#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#           ref: ${{env.BRANCH}} 
#           token: ${{ secrets.MY_PAT }}
#           fetch-depth: 0

#     - name: Branch name
#       run: echo running on branch ${GITHUB_HEAD_REF##*/}

#     - name: Set Tag Name
#       id: artifact_version
#       run: echo "artifact_version=${{env.BASE_TAG}}.$(date +'%Y-%m-%d').b${{github.run_number}}" >> $GITHUB_ENV 

#     - name: artifact version
#       run: echo newly set env variable ${{env.BASE_TAG}}

#     - name: container tag
#       run: echo newly set env variable ${{env.artifact_version}}

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - id: "lower_repo"
#       uses: ASzc/change-string-case-action@v2
#       with:
#         string: ${{ github.event.repository.name }}

#     - name: Authenticate with the Github Container Registry ğŸ”
#       run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

#     - name: Build and push docker image ğŸ— ğŸ“¦
#       id: build-n-push
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: Dockerfile
#         platforms: linux/amd64
#         push: true
#         tags: ghcr.io/raganhar/${{steps.lower_repo.outputs.lowercase}}:${{env.artifact_version}}

#     - name: Create tag
#       if: steps.build-n-push.outcome == 'success' 
#       run: |
#         git tag ${{ env.artifact_version }}
#         git push --tags